sudo: true
dist: trusty
language: perl
python: 2.7.10
perl:
- '5.26'
- '5.14'
addons:
  apt:
    packages:
    - libdb-dev
    - libgd2-noxpm-dev
  firefox: '58.0'
cache:
  yarn: true
  directories:
  - extlib/
  - "$HOME/perl5/"
  - node_modules/
  - "$HOME/python/"
  - "$HOME/.nvm/"
before_install:
- openssl aes-256-cbc -K $encrypted_a33f2fb5219d_key -iv $encrypted_a33f2fb5219d_iv -in website/deploy.pem.enc -out website/deploy.pem -d
- ls website
- chmod 600 website/deploy.pem
- sudo dpkg --add-architecture i386
- sudo apt-get -qq update
- sudo apt-get install wine1.6
install:
- phantomjs --version
- wget -O - https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
  | tar -xzf - -C ~/geckodriver_$GECKODRIVER_VERSION;
- export PATH=$PATH:$HOME/geckodriver_$GECKODRIVER_VERSION
- cpanm --notest GD::Image Text::Markdown DateTime JSON
- if [[ ! -f ~/python/bin/activate ]]; then virtualenv ~/python; fi
- source ~/python/bin/activate
- pip install nose selenium
script:
- if [[ "x$TRAVIS_TAG" != "x" ]]; then build/set_package_versions.pl $TRAVIS_TAG src/JBrowse/package.json
  package.json; fi
- RELEASE_VERSION=`node -e 'require("fs").readFile("src/JBrowse/package.json", (e,d)=>console.log(JSON.parse(d).version))'`
- BUILD_DIR=$PWD
- set -e
- "./setup.sh"
- yarn lint
- prove -Isrc/perl5 -r -j3 tests/perl_tests;
- utils/jb_run.js -p 9000 & sleep 2
- phantomjs tests/js_tests/run-jasmine.js http://localhost:9000/tests/js_tests/index.html
- utils/jb_run.js -p 8000 -s jbrowse & sleep 2
- phantomjs tests/js_tests/run-jasmine.js http://localhost:8000/jbrowse/tests/js_tests/index.html
- xvfb-run npm test-electron
- MOZ_HEADLESS=1 SELENIUM_BROWSER=firefox JBROWSE_URL=http://localhost:9000/index.html
  tests/selenium_tests/travis_wrapper.sh;
- |
  if [[ "x$TRAVIS_TAG" != "x" || $TRAVIS_BRANCH = "master" || $TRAVIS_BRANCH = "dev" || $TRAVIS_PULL_REQUEST != "false" ]]; then
    make -f build/Makefile;
    rm -rf JBrowse-*/;
    unzip -q JBrowse-$RELEASE_VERSION.zip;
    cd JBrowse-$RELEASE_VERSION/;
    cp -r ../tests/ .;
    ./setup.sh;
    prove -Isrc/perl5 -r -j3 tests/perl_tests;
    cd $BUILD_DIR;
    MOZ_HEADLESS=1 SELENIUM_BROWSER=firefox NOSEOPTS="-I jasmine" JBROWSE_URL=http://localhost:9000/JBrowse-$RELEASE_VERSION/index.html tests/selenium_tests/travis_wrapper.sh;
  fi
- set +e
after_failure:
- cat setup.log
deploy:
- provider: releases
  api_key:
    secure: BuOD7rqrcGKT3g0hVY5AGpJI/Kkko4DhSIYSUQ28sS2AOdoNyTD0t5doL/Kiq4BC41q198tbFFt1dnXGdo8YKpBSXO/uGUuuiGtMFHM++I84oLq20p49iyrenNZ4m/jy/Q4YtizIYLs83DVzVdQzhJ5hrTx6f+d1gc9EgaMeBF4=
  file: JBrowse-1.*.zip
  file_glob: true
  skip_cleanup: true
  on:
    repo: GMOD/jbrowse
    perl: 5.26
    tags: true
- provider: npm
  email: rbuels@gmail.com
  skip_cleanup: true
  api_key:
    secure: OpxHZGvyCFeG2CUpw4dHTz3kFBHJXeET2c4XxwKMxtL2FVt4W/zDLUV0gLQDFfsLlj+zjF62qtbHU8MajMw3aFLlTIdMIit+2s6H4D8kuBh5Q7pO5/gAykWtiwkJ3BudoYDGoDlB5kkakG4MPvvY26490hbmySCSgpsjetM91zE=
  on:
    repo: GMOD/jbrowse
    perl: 5.26
    tags: true
- provider: script
  script: website/deploy.sh
  skip_cleanup: true
  on:
    perl: 5.26
    tags: true
